# Generated by Django 3.1 on 2022-01-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingtrajectory',
            name='city',
        ),
        migrations.RemoveField(
            model_name='trackingtrajectory',
            name='state',
        ),
    ]
