# Generated by Django 3.1 on 2022-01-10 04:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220105_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonGeofence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', models.JSONField(default=api.models.json_polygon_file)),
            ],
        ),
    ]
