name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "[API]: Build the Docker image"
      run: |
        cd geoapi
        docker build . -f Dockerfile --tag geoapi:$(date +%s)
    - name: "[APP]: Build the Docker image"
      run: |
        cd geoapp
        docker build . -f Dockerfile --tag geoapp:$(date +%s)
